//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.10.27 at 02:18:48 PM CEST 
//


package pkowalski.rtcp.xml;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the pkowalski.rtcp.xml package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _RtcpnetPagesPageArcsArcIconBreakpoint_QNAME = new QName("", "breakpoint");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: pkowalski.rtcp.xml
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Rtcpnet.Pages.Page.Places.Place.Icon.TypeLabel }
     * 
     */
    public Rtcpnet.Pages.Page.Places.Place.Icon.TypeLabel createRtcpnetPagesPagePlacesPlaceIconTypeLabel() {
        return new Rtcpnet.Pages.Page.Places.Place.Icon.TypeLabel();
    }

    /**
     * Create an instance of {@link Rtcpnet.Hierarchy.Nodes }
     * 
     */
    public Rtcpnet.Hierarchy.Nodes createRtcpnetHierarchyNodes() {
        return new Rtcpnet.Hierarchy.Nodes();
    }

    /**
     * Create an instance of {@link Rtcpnet.Hierarchy.Nodes.Node.Icon.NameLabel }
     * 
     */
    public Rtcpnet.Hierarchy.Nodes.Node.Icon.NameLabel createRtcpnetHierarchyNodesNodeIconNameLabel() {
        return new Rtcpnet.Hierarchy.Nodes.Node.Icon.NameLabel();
    }

    /**
     * Create an instance of {@link Rtcpnet.Pages.Page.Transitions }
     * 
     */
    public Rtcpnet.Pages.Page.Transitions createRtcpnetPagesPageTransitions() {
        return new Rtcpnet.Pages.Page.Transitions();
    }

    /**
     * Create an instance of {@link Rtcpnet.Pages.Page.Transitions.Transition.Icon.GuardLabel }
     * 
     */
    public Rtcpnet.Pages.Page.Transitions.Transition.Icon.GuardLabel createRtcpnetPagesPageTransitionsTransitionIconGuardLabel() {
        return new Rtcpnet.Pages.Page.Transitions.Transition.Icon.GuardLabel();
    }

    /**
     * Create an instance of {@link Rtcpnet.Pages }
     * 
     */
    public Rtcpnet.Pages createRtcpnetPages() {
        return new Rtcpnet.Pages();
    }

    /**
     * Create an instance of {@link Rtcpnet.Pages.Page.Places.Place.Icon.MarkingLabel }
     * 
     */
    public Rtcpnet.Pages.Page.Places.Place.Icon.MarkingLabel createRtcpnetPagesPagePlacesPlaceIconMarkingLabel() {
        return new Rtcpnet.Pages.Page.Places.Place.Icon.MarkingLabel();
    }

    /**
     * Create an instance of {@link Rtcpnet.Hierarchy.Connections }
     * 
     */
    public Rtcpnet.Hierarchy.Connections createRtcpnetHierarchyConnections() {
        return new Rtcpnet.Hierarchy.Connections();
    }

    /**
     * Create an instance of {@link Rtcpnet.Hierarchy.Nodes.Node.Icon.ParametersLabel }
     * 
     */
    public Rtcpnet.Hierarchy.Nodes.Node.Icon.ParametersLabel createRtcpnetHierarchyNodesNodeIconParametersLabel() {
        return new Rtcpnet.Hierarchy.Nodes.Node.Icon.ParametersLabel();
    }

    /**
     * Create an instance of {@link Rtcpnet.Hierarchy }
     * 
     */
    public Rtcpnet.Hierarchy createRtcpnetHierarchy() {
        return new Rtcpnet.Hierarchy();
    }

    /**
     * Create an instance of {@link Rtcpnet.Pages.Page.Transitions.Transition.Icon.NameLabel }
     * 
     */
    public Rtcpnet.Pages.Page.Transitions.Transition.Icon.NameLabel createRtcpnetPagesPageTransitionsTransitionIconNameLabel() {
        return new Rtcpnet.Pages.Page.Transitions.Transition.Icon.NameLabel();
    }

    /**
     * Create an instance of {@link Rtcpnet.Pages.Page.Places.Place.Icon.NameLabel }
     * 
     */
    public Rtcpnet.Pages.Page.Places.Place.Icon.NameLabel createRtcpnetPagesPagePlacesPlaceIconNameLabel() {
        return new Rtcpnet.Pages.Page.Places.Place.Icon.NameLabel();
    }

    /**
     * Create an instance of {@link Rtcpnet.Hierarchy.Connections.Connection.Icon.Breakpoint }
     * 
     */
    public Rtcpnet.Hierarchy.Connections.Connection.Icon.Breakpoint createRtcpnetHierarchyConnectionsConnectionIconBreakpoint() {
        return new Rtcpnet.Hierarchy.Connections.Connection.Icon.Breakpoint();
    }

    /**
     * Create an instance of {@link Rtcpnet.Pages.Page.Transitions.Transition }
     * 
     */
    public Rtcpnet.Pages.Page.Transitions.Transition createRtcpnetPagesPageTransitionsTransition() {
        return new Rtcpnet.Pages.Page.Transitions.Transition();
    }

    /**
     * Create an instance of {@link Rtcpnet.Pages.Page.Arcs.Arc }
     * 
     */
    public Rtcpnet.Pages.Page.Arcs.Arc createRtcpnetPagesPageArcsArc() {
        return new Rtcpnet.Pages.Page.Arcs.Arc();
    }

    /**
     * Create an instance of {@link Rtcpnet.Pages.Page.Places }
     * 
     */
    public Rtcpnet.Pages.Page.Places createRtcpnetPagesPagePlaces() {
        return new Rtcpnet.Pages.Page.Places();
    }

    /**
     * Create an instance of {@link Rtcpnet.Pages.Page }
     * 
     */
    public Rtcpnet.Pages.Page createRtcpnetPagesPage() {
        return new Rtcpnet.Pages.Page();
    }

    /**
     * Create an instance of {@link Rtcpnet.Pages.Page.Arcs.Arc.Icon.Breakpoint }
     * 
     */
    public Rtcpnet.Pages.Page.Arcs.Arc.Icon.Breakpoint createRtcpnetPagesPageArcsArcIconBreakpoint() {
        return new Rtcpnet.Pages.Page.Arcs.Arc.Icon.Breakpoint();
    }

    /**
     * Create an instance of {@link Rtcpnet.Hierarchy.Connections.Connection }
     * 
     */
    public Rtcpnet.Hierarchy.Connections.Connection createRtcpnetHierarchyConnectionsConnection() {
        return new Rtcpnet.Hierarchy.Connections.Connection();
    }

    /**
     * Create an instance of {@link Rtcpnet.Pages.Page.Transitions.Transition.Icon }
     * 
     */
    public Rtcpnet.Pages.Page.Transitions.Transition.Icon createRtcpnetPagesPageTransitionsTransitionIcon() {
        return new Rtcpnet.Pages.Page.Transitions.Transition.Icon();
    }

    /**
     * Create an instance of {@link Rtcpnet.Pages.Page.Arcs }
     * 
     */
    public Rtcpnet.Pages.Page.Arcs createRtcpnetPagesPageArcs() {
        return new Rtcpnet.Pages.Page.Arcs();
    }

    /**
     * Create an instance of {@link Rtcpnet.Pages.Page.Places.Place.Icon.PortLabel }
     * 
     */
    public Rtcpnet.Pages.Page.Places.Place.Icon.PortLabel createRtcpnetPagesPagePlacesPlaceIconPortLabel() {
        return new Rtcpnet.Pages.Page.Places.Place.Icon.PortLabel();
    }

    /**
     * Create an instance of {@link Rtcpnet.Pages.Page.Places.Place }
     * 
     */
    public Rtcpnet.Pages.Page.Places.Place createRtcpnetPagesPagePlacesPlace() {
        return new Rtcpnet.Pages.Page.Places.Place();
    }

    /**
     * Create an instance of {@link Rtcpnet.Pages.Page.Places.Place.Icon }
     * 
     */
    public Rtcpnet.Pages.Page.Places.Place.Icon createRtcpnetPagesPagePlacesPlaceIcon() {
        return new Rtcpnet.Pages.Page.Places.Place.Icon();
    }

    /**
     * Create an instance of {@link Rtcpnet.Pages.Page.Transitions.Transition.Icon.PriorityLabel }
     * 
     */
    public Rtcpnet.Pages.Page.Transitions.Transition.Icon.PriorityLabel createRtcpnetPagesPageTransitionsTransitionIconPriorityLabel() {
        return new Rtcpnet.Pages.Page.Transitions.Transition.Icon.PriorityLabel();
    }

    /**
     * Create an instance of {@link Rtcpnet.Pages.Page.Transitions.Transition.Icon.SubstitutionLabel }
     * 
     */
    public Rtcpnet.Pages.Page.Transitions.Transition.Icon.SubstitutionLabel createRtcpnetPagesPageTransitionsTransitionIconSubstitutionLabel() {
        return new Rtcpnet.Pages.Page.Transitions.Transition.Icon.SubstitutionLabel();
    }

    /**
     * Create an instance of {@link Rtcpnet.Pages.Page.Arcs.Arc.Icon }
     * 
     */
    public Rtcpnet.Pages.Page.Arcs.Arc.Icon createRtcpnetPagesPageArcsArcIcon() {
        return new Rtcpnet.Pages.Page.Arcs.Arc.Icon();
    }

    /**
     * Create an instance of {@link Rtcpnet.Pages.Page.Places.Place.Icon.FusionLabel }
     * 
     */
    public Rtcpnet.Pages.Page.Places.Place.Icon.FusionLabel createRtcpnetPagesPagePlacesPlaceIconFusionLabel() {
        return new Rtcpnet.Pages.Page.Places.Place.Icon.FusionLabel();
    }

    /**
     * Create an instance of {@link Rtcpnet }
     * 
     */
    public Rtcpnet createRtcpnet() {
        return new Rtcpnet();
    }

    /**
     * Create an instance of {@link Rtcpnet.Hierarchy.Connections.Connection.Icon }
     * 
     */
    public Rtcpnet.Hierarchy.Connections.Connection.Icon createRtcpnetHierarchyConnectionsConnectionIcon() {
        return new Rtcpnet.Hierarchy.Connections.Connection.Icon();
    }

    /**
     * Create an instance of {@link Rtcpnet.Hierarchy.Nodes.Node.Icon }
     * 
     */
    public Rtcpnet.Hierarchy.Nodes.Node.Icon createRtcpnetHierarchyNodesNodeIcon() {
        return new Rtcpnet.Hierarchy.Nodes.Node.Icon();
    }

    /**
     * Create an instance of {@link Rtcpnet.Hierarchy.Nodes.Node }
     * 
     */
    public Rtcpnet.Hierarchy.Nodes.Node createRtcpnetHierarchyNodesNode() {
        return new Rtcpnet.Hierarchy.Nodes.Node();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Rtcpnet.Pages.Page.Arcs.Arc.Icon.Breakpoint }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "breakpoint", scope = Rtcpnet.Pages.Page.Arcs.Arc.Icon.class)
    public JAXBElement<Rtcpnet.Pages.Page.Arcs.Arc.Icon.Breakpoint> createRtcpnetPagesPageArcsArcIconBreakpoint(Rtcpnet.Pages.Page.Arcs.Arc.Icon.Breakpoint value) {
        return new JAXBElement<Rtcpnet.Pages.Page.Arcs.Arc.Icon.Breakpoint>(_RtcpnetPagesPageArcsArcIconBreakpoint_QNAME, Rtcpnet.Pages.Page.Arcs.Arc.Icon.Breakpoint.class, Rtcpnet.Pages.Page.Arcs.Arc.Icon.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Rtcpnet.Hierarchy.Connections.Connection.Icon.Breakpoint }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "breakpoint", scope = Rtcpnet.Hierarchy.Connections.Connection.Icon.class)
    public JAXBElement<Rtcpnet.Hierarchy.Connections.Connection.Icon.Breakpoint> createRtcpnetHierarchyConnectionsConnectionIconBreakpoint(Rtcpnet.Hierarchy.Connections.Connection.Icon.Breakpoint value) {
        return new JAXBElement<Rtcpnet.Hierarchy.Connections.Connection.Icon.Breakpoint>(_RtcpnetPagesPageArcsArcIconBreakpoint_QNAME, Rtcpnet.Hierarchy.Connections.Connection.Icon.Breakpoint.class, Rtcpnet.Hierarchy.Connections.Connection.Icon.class, value);
    }

}
